Repository BuildOnViction/tomomaster, pull requests merged in 2018-07, with the labels that each got.

#96 Add CD/CI pipeline
  .travis.yml
  Dockerfile
  Dockerfile.old
  docker-stack.yml
  docker_push.sh
  docker_rebuild.sh
  entrypoint.sh
Labels: CI/CD

#103 Update travis.tml stage order
  .travis.yml
Labels: CI/CD

#122 Add pipeline for tagged release
  .travis.yml
  docker_push.sh
Labels: CI/CD

#124 Fix missing check repo check for PR
  .travis.yml
Labels: CI/CD

#126 Update new UI for chart
  app/app.js
  app/assets/scss/components/_chart.scss
  app/assets/scss/style.scss
  app/components/Chart.vue
  app/components/blocksigners/List.vue
  app/components/candidates/List.vue
  app/components/candidates/View.vue
  app/components/candidates/Withdraw.vue
  app/components/voters/View.vue
  package-lock.json
  package.json
Labels: review

#129 add apply candidate api
  apis/candidates.js
  package-lock.json
  package.json
Labels: review

#130 fix #127
  app/app.js
  app/assets/scss/components/_info.scss
  app/assets/scss/trumps/_custom.scss
  app/components/candidates/List.vue
  app/components/candidates/View.vue
  app/components/voters/View.vue
  app/components/voters/Voting.vue
Labels: review

#131 Fix travis build stage
  .travis.yml
  docker_push.sh
  docker_rebuild.sh
Labels: CI/CD, bug, review

#132 Update .travis.yml
  .travis.yml
Labels: CI/CD, bug, review
