Repository BuildOnViction/tomomaster, pull requests merged in 2018-11, with the labels that each got.

#276 fix bug cant unvote
  app/components/candidates/View.vue
  app/components/voters/Unvoting.vue
Labels: review

#278 Change text Withdrawls
  app/components/Setting.vue
Labels: review

#279 update masternode reward table to show only masternode reward
  apis/candidates.js
  app/assets/scss/components/_table.scss
  app/components/candidates/View.vue
Labels: review

#280 remove sorting by age
  app/components/candidates/View.vue
  app/components/voters/View.vue
Labels: review

#281 Disable withdrawal button when current blk < wd blk
  app/assets/scss/trumps/_custom.scss
  app/components/Setting.vue
Labels: review

#253 Vote & unvote by TomoWallet
  apis/voters.js
  app/app.js
  app/assets/scss/trumps/_custom.scss
  app/components/voters/Unvoting.vue
  app/components/voters/Voting.vue
  config/custom-environment-variables.json
  config/default.json
  models/mongodb/signTransaction.js
  package-lock.json
  package.json
Labels: review

#292 update travis for deployment in devnet
  .travis.yml
Labels: CI/CD

#312 improve phrasing of login required toast
  app/components/candidates/List.vue
Labels: UX
