Repository BuildOnViction/tomomaster, pull requests merged in 2018-08, with the labels that each got.

#134 update package lock file
  package-lock.json
Labels: review

#136 fix bug of NumberInput component
  app/components/NumberInput.vue
  package-lock.json
Labels: review

#137 fix 'next checkpoint' formula
  app/components/candidates/List.vue
Labels: review

#140 remove unused code
  app/components/candidates/List.vue
Labels: review

#141 Remove nodeUrl, add nodeId, add abi files
  abis.js
  abis/BlockSigner.json
  abis/Migrations.json
  abis/SafeMath.json
  abis/TomoRandomize.json
  abis/TomoValidator.json
  app/components/candidates/Apply.vue
  contracts/TomoValidator.sol
  models/mongodb/candidate.js
  package.json
  services/crawl.js
  test/TomoValidatorTest.js
Labels: review

#142 Refactor Dockerfile
  Dockerfile
  config/custom-environment-variables.json
  package.json
Labels: Docker, review

#144 handle mongodb connect error
  apis/candidates.js
  models/mongodb/index.js
Labels: review

#146 add withdraw page for voter and masternode owner
  Dockerfile.old
  abis/BlockSigner.json
  abis/Migrations.json
  abis/SafeMath.json
  abis/TomoRandomize.json
  abis/TomoValidator.json
  apis/candidates.js
  apis/index.js
  apis/owners.js
  app/components/Setting.vue
  app/components/candidates/View.vue
  app/components/voters/Confirm.vue
  contracts/TomoValidator.sol
  models/mongodb/withdraw.js
  services/crawl.js
Labels: review

#149 add kue, cal reward
  abis/SafeMath.json
  abis/TomoValidator.json
  config/custom-environment-variables.json
  config/default.json
  contracts/TomoValidator.sol
  models/blockchain/chain.js
  models/mongodb/blockSigner.js
  models/mongodb/reward.js
  package-lock.json
  package.json
  queues/index.js
  queues/reward.js
  services/crawl.js
Labels: review

#154 remove nodeId, move to form apply
  abis/BlockSigner.json
  abis/Migrations.json
  abis/SafeMath.json
  abis/TomoRandomize.json
  abis/TomoValidator.json
  app/components/candidates/Apply.vue
  app/components/candidates/View.vue
  contracts/TomoValidator.sol
  queues/reward.js
  services/crawl.js
  test/TomoValidatorTest.js
Labels: review

#155 reward foundation, loading withdraw
  app/components/Setting.vue
  app/components/candidates/View.vue
  config/default.json
  models/mongodb/fdReward.js
  queues/reward.js
Labels: review

#156 fix reward count from
  config/default.json
  queues/reward.js
Labels: review

#157 fix bug reward, after review smart contract
  abis/BlockSigner.json
  abis/Migrations.json
  abis/SafeMath.json
  abis/TomoRandomize.json
  abis/TomoValidator.json
  contracts/TomoValidator.sol
  queues/reward.js
Labels: review

#159 add minvotercap
  app/components/voters/Voting.vue
  config/default.json
  contracts/TomoValidator.sol
  migrations/2_deploy_contracts.js
  test/TomoValidatorTest.js
Labels: review

#160 fix bug withdraw index
  app/components/Setting.vue
Labels: review

#161 cmd to update candidate info
  .eslintignore
  app/components/Chart.vue
  app/components/candidates/View.vue
  cmd.js
  models/mongodb/candidate.js
  package-lock.json
  package.json
  services/crawl.js
Labels: review

#162 fix currency symbol
  app/app.js
Labels: review

#164 change message for tomomaster
  app/components/candidates/Resign.vue
Labels: review

#167 Update .travis.yml
  .travis.yml
Labels: CI/CD, review

#168 add favicon to header of the page
  app/assets/img/favicon.png
  index.html
Labels: review

#169 add meta description to header
  index.html
Labels: review

#174 add search candidate, voter
  apis/index.js
  apis/search.js
  app/App.vue
Labels: review

#175 add simple GA
  apis/config.js
  app/app.js
  config/default.json
  package-lock.json
  package.json
Labels: review

#176 add Age column
  app/assets/scss/components/_table.scss
  app/components/candidates/View.vue
  app/components/voters/View.vue
  package-lock.json
  package.json
Labels: review

#179 add-transaction-table-voter
  app/components/voters/View.vue
  package-lock.json
Labels: review

#177 issue parallel save
  app/assets/scss/components/_table.scss
  app/components/Setting.vue
  index.js
  package-lock.json
  package.json
  services/crawl.js
Labels: review

#180 fix build image
  package-lock.json
  package.json
Labels: review

#182 Hide social network icons when not available
  app/components/candidates/View.vue
  cmd.js
Labels: review
